#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Feb 02 14:50:24 CET 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim usb_interface_tb_func_impl -key {Post-Implementation:sim_1:Functional:usb_interface_tb} -tclbatch usb_interface_tb.tcl -view /home/rzinkstok/usb_interface/fpga/usb_interface_tb_behav.wcfg -log simulate.log"
xsim usb_interface_tb_func_impl -key {Post-Implementation:sim_1:Functional:usb_interface_tb} -tclbatch usb_interface_tb.tcl -view /home/rzinkstok/usb_interface/fpga/usb_interface_tb_behav.wcfg -log simulate.log

