#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 28 18:22:04 CET 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim toplevel_tb_behav -key {Behavioral:sim_1:Functional:toplevel_tb} -tclbatch toplevel_tb.tcl -view /home/rzinkstok/usb_interface/fpga/usb_interface_tb_behav.wcfg -log simulate.log"
xsim toplevel_tb_behav -key {Behavioral:sim_1:Functional:toplevel_tb} -tclbatch toplevel_tb.tcl -view /home/rzinkstok/usb_interface/fpga/usb_interface_tb_behav.wcfg -log simulate.log

